

#pragma once

#include "ui/ZmodUI.h"

namespace Store {

struct PackEntry {
    const char* id;
    const char* label;
    const char* category;
    int         priceInGems;
};

static const char* const kCategories[] = {
    "All",
    "Kits", "Themes", "FashionPack", "Seeds", "Locks", "Fishing",
    "Familiars", "Pets", "Orbs", "Cards", "Wiring", "Items",
    "Nether", "Blueprints", "Community", "Clan",
};
inline constexpr int kCategoryCount = (int)(sizeof(kCategories) / sizeof(kCategories[0]));

static const PackEntry kPackCatalog[] = {

    { "HomeKit", "Home Kit", "Kits", 500 },
    { "FishingKit", "Fishing Kit", "Kits", 1500 },
    { "SnowcastleKit", "Snowcastle Kit", "Kits", 7500 },
    { "WinterDecoKit", "Winter Deco Kit", "Kits", 7500 },
    { "SummerKit", "Summer Kit", "Kits", 14500 },
    { "TreeKit", "Tree Kit", "Kits", 1450 },
    { "GardenKit", "Garden Kit", "Kits", 2000 },
    { "DecorationKit", "Decoration Kit", "Kits", 2500 },
    { "CastleKit", "Castle Kit", "Kits", 4500 },
    { "DashPack", "Dash Pack", "Kits", 4500 },
    { "UnderwaterKit", "Underwater Kit", "Kits", 7500 },
    { "AlienPlanetKit", "Alien Planet Kit", "Kits", 12000 },
    { "WolfSuitKit", "Wolf Suit Kit", "Kits", 9999999 },
    { "PigSuitKit", "Pig Suit Kit", "Kits", 9999999 },
    { "RaccoonSuitKit", "Raccoon Suit Kit", "Kits", 9999999 },
    { "BumblebeeSuitKit", "Bumblebee Suit Kit", "Kits", 9999999 },
    { "MallardSuitKit", "Mallard Suit Kit", "Kits", 9999999 },
    { "KangarooSuitKit", "Kangaroo Suit Kit", "Kits", 9999999 },

    { "FireworksBooster", "Fireworks Booster", "Themes", 300 },
    { "SaintPatricksBooster", "Saintpatricks Booster", "Themes", 800 },
    { "Candyworldbooster", "Candyworld Booster", "Themes", 900 },
    { "NetherMiniboss1Booster", "Nether Miniboss1 Booster", "Themes", 99999 },
    { "Eastereggbooster", "Easter Egg Booster", "Themes", 99999 },
    { "Easterbooster", "Easter Booster", "Themes", 800 },
    { "xmaspack", "Xmas Booster", "Themes", 900 },
    { "AncientTimesBooster", "Ancient Times Booster", "Themes", 999 },
    { "scifipack", "Scifi Booster", "Themes", 500 },
    { "PlatformerBooster", "Platformer Booster", "Themes", 500 },
    { "MedievalPack", "Medieval Booster", "Themes", 550 },
    { "GangstaPack", "Gangsta Booster", "Themes", 700 },
    { "SamuraiBooster", "Samurai Booster", "Themes", 999 },
    { "VikingBooster", "Viking Booster", "Themes", 999 },
    { "UrbanBooster", "Urban Booster", "Themes", 999 },
    { "ElfBooster", "Elf Booster", "Themes", 999 },
    { "ChaosBooster", "Chaos Booster", "Themes", 999 },
    { "PirateBooster", "Pirate Booster", "Themes", 999 },
    { "AlienBooster", "Alien Booster", "Themes", 999 },
    { "Shardbooster", "Shard Booster", "Themes", 1000 },
    { "HalloweenBooster1", "Halloween Booster 1", "Themes", 666 },
    { "HalloweenBooster2", "Halloween Booster 2", "Themes", 666 },
    { "HalloweenBooster3", "Halloween Booster 3", "Themes", 666 },
    { "HalloweenBooster4", "Halloween Booster 4", "Themes", 666 },
    { "Superherobooster1", "Super Hero Booster 1", "Themes", 500 },
    { "Superherobooster2", "Super Hero Booster 2", "Themes", 500 },
    { "Superherobooster3", "Super Hero Booster 3", "Themes", 500 },
    { "Superherobooster4", "Super Hero Booster 4", "Themes", 500 },
    { "Superherobooster5", "Super Hero Booster 5", "Themes", 500 },
    { "Superherobooster6", "Super Hero Booster 6", "Themes", 500 },
    { "Superherobooster7", "Super Hero Booster 7", "Themes", 500 },
    { "Superherobooster8", "Super Hero Booster 8", "Themes", 500 },
    { "Superherobooster9", "Super Hero Booster 9", "Themes", 500 },
    { "Superherobooster10", "Super Hero Booster 10", "Themes", 500 },
    { "Superherobooster11", "Super Hero Booster 11", "Themes", 500 },
    { "Superherobooster12", "Super Hero Booster 12", "Themes", 500 },

    { "BasicClothes", "Basic Clothes", "FashionPack", 50 },
    { "ProClothes", "Pro Clothes", "FashionPack", 500 },
    { "RareHairPackI", "Rare Hair Pack I", "FashionPack", 3500 },
    { "WeaponSunHammer", "Sun Hammer", "FashionPack", 20000 },
    { "WeaponSummerHammer", "Summer Hammer", "FashionPack", 15000 },
    { "HatSteampunk", "Steampunk Hat", "FashionPack", 1250 },
    { "ContactLensesSnake", "Snake Contact Lenses", "FashionPack", 120000 },
    { "FrostWings", "Frost Wings", "FashionPack", 100000 },
    { "SuitGhost", "Ghost Suit", "FashionPack", 425000 },
    { "SuitGhostBlue", "Ghost Suit (Blue)", "FashionPack", 425000 },
    { "SuitGhostPurple", "Ghost Suit (Purple)", "FashionPack", 425000 },
    { "SuitGhostOrange", "Ghost Suit (Orange)", "FashionPack", 425000 },
    { "SuitGhostRed", "Ghost Suit (Red)", "FashionPack", 425000 },
    { "VikingHairPack", "Viking Hair Pack", "FashionPack", 550 },
    { "SupportHoodie", "Support Hoodie", "FashionPack", 10000 },
    { "PinkSupportHoodie", "Pink Support Hoodie", "FashionPack", 10000 },
    { "PixieWings", "Pixie Wings", "FashionPack", 7500 },
    { "WingsDemon", "Demon Wings", "FashionPack", 12000 },
    { "BlueDragonWings", "Blue Dragon Wings", "FashionPack", 75000 },
    { "WingsDragonBlack", "Black Dragon Wings", "FashionPack", 150000 },
    { "SodaJetpack", "Soda Jetpack", "FashionPack", 400000 },
    { "BlueContactLenses", "Blue Contact Lenses", "FashionPack", 7500 },
    { "GreenContactLenses", "Green Contact Lenses", "FashionPack", 7500 },
    { "BrownContactLenses", "Brown Contact Lenses", "FashionPack", 7500 },
    { "SilverContactLenses", "Silver Contact Lenses", "FashionPack", 18000 },
    { "TurquoiseContactLenses", "Turquoise Contact Lenses", "FashionPack", 22000 },
    { "GoldContactLenses", "Gold Contact Lenses", "FashionPack", 28000 },
    { "PurpleContactLenses", "Purple Contact Lenses", "FashionPack", 30000 },
    { "PinkContactLenses", "Pink Contact Lenses", "FashionPack", 30000 },
    { "WhiteContactLenses", "White Contact Lenses", "FashionPack", 125000 },
    { "RedContactLenses", "Red Contact Lenses", "FashionPack", 150000 },
    { "AlienContactLenses", "Alien Contact Lenses", "FashionPack", 300000 },
    { "GoblinRing", "Goblin Ring", "FashionPack", 60000 },
    { "FrostRing", "Frost Ring", "FashionPack", 150000 },
    { "DemonRing", "Demon Ring", "FashionPack", 150000 },
    { "YellowRing", "Yellow Ring", "FashionPack", 200000 },
    { "TurquoiseRing", "Turquoise Ring", "FashionPack", 225000 },
    { "RoseRing", "Rose Ring", "FashionPack", 250000 },

    { "WinterPack", "Winter Pack", "Seeds", 2800 },
    { "Fertilizer", "Fertilizer", "Seeds", 150 },
    { "FertilizerLarge", "Fertilizer (Large)", "Seeds", 300 },
    { "BasicSeeds", "Basic Seeds", "Seeds", 50 },
    { "AdvancedSeeds", "Advanced Seeds", "Seeds", 500 },
    { "RockPack", "Rock Pack", "Seeds", 500 },
    { "Water", "Where's My Water?", "Seeds", 1000 },
    { "SandPack", "Sand Pack", "Seeds", 1000 },

    { "SmallLock", "Small Lock", "Locks", 100 },
    { "MediumLock", "Medium Lock", "Locks", 500 },
    { "LargeLock", "Large Lock", "Locks", 1000 },
    { "WorldLock", "World Lock", "Locks", 3500 },
    { "DarkLock", "Dark Lock", "Locks", 28000 },
    { "PlatinumLock", "Platinum Lock", "Locks", 350000 },
    { "BattleLock", "Battle Lock", "Locks", 3000 },
    { "BattleWorldLock", "Battle World Lock", "Locks", 7500 },

    { "LureBooster", "Lure Booster", "Fishing", 100 },
    { "LureBoosterLarge", "Large Lure Booster", "Fishing", 500 },
    { "FishingRodBambooBasic", "Fishing Rod (Bamboo)", "Fishing", 500 },
    { "FishingRodFiberglassBasic", "Fishing Rod (Fiberglass)", "Fishing", 2500 },
    { "FishingRodCarbonFiberBasic", "Fishing Rod (Carbon Fiber)", "Fishing", 15000 },
    { "FishingRodTitaniumBasic", "Fishing Rod (Titanium)", "Fishing", 35000 },
    { "FishingRodUpgradeStation", "Fishing Rod Upgrade Station", "Fishing", 10000 },
    { "FishingScoreBoard", "Fishing Score Board", "Fishing", 15000 },
    { "FishingRecycler", "Fishing Recycler", "Fishing", 20000 },

    { "Heart", "Heart Familiar", "Familiars", 55000 },
    { "Snowman", "Snowman Familiar", "Familiars", 55000 },
    { "Penguin", "Penguin Familiar", "Familiars", 70000 },
    { "Eye", "Eye Familiar", "Familiars", 45000 },
    { "Pumpkin", "Pumpkin Familiar", "Familiars", 65000 },
    { "Skull", "Skull Familiar", "Familiars", 100000 },
    { "Ghost", "Ghost Familiar", "Familiars", 90000 },
    { "Bat", "Bat Familiar", "Familiars", 130000 },
    { "Squid", "Squid Familiar", "Familiars", 70000 },
    { "Sun", "Sun Familiar", "Familiars", 45000 },
    { "Turtle", "Turtle Familiar", "Familiars", 80000 },
    { "Clover", "Clover Familiar", "Familiars", 47000 },
    { "Bunny", "Bunny Familiar", "Familiars", 35000 },
    { "Gem", "Gem Familiar", "Familiars", 45000 },
    { "Crow", "Crow Familiar", "Familiars", 50000 },
    { "Mini-bot", "Mini-bot Familiar", "Familiars", 65000 },
    { "Gremlin", "Gremlin Familiar", "Familiars", 75000 },
    { "Lock", "Lock Familiar", "Familiars", 75000 },
    { "Parrot", "Parrot Familiar", "Familiars", 85000 },
    { "FamiliarBlockSoil", "Soil Familiar", "Familiars", 9999999 },
    { "FamiliarBlockWood", "Wood Familiar", "Familiars", 9999999 },
    { "FamiliarBlockMarble", "Marble Familiar", "Familiars", 9999999 },
    { "FamiliarBlockSteel", "Steel Familiar", "Familiars", 9999999 },
    { "FamiliarBlockObsidian", "Obsidian Familiar", "Familiars", 9999999 },
    { "FamiliarBlockMagicstuff", "Magic Stuff Familiar", "Familiars", 9999999 },
    { "FamiliarBlockSand", "Sand Familiar", "Familiars", 9999999 },
    { "FamiliarBlockGranite", "Granite Familiar", "Familiars", 9999999 },
    { "FamiliarBlockWater", "Water Familiar", "Familiars", 9999999 },
    { "FamiliarBlockLava", "Lava Familiar", "Familiars", 9999999 },
    { "FamiliarTeddy", "Teddy Bear Familiar", "Familiars", 9999999 },
    { "FAMEvolverator", "Familiar Evolverator", "Familiars", 35000 },
    { "FAMFoodMachine", "Familiar Food Machine", "Familiars", 50000 },

    { "VirtualPetDog", "Virtual Pet Dog", "Pets", 10000 },
    { "VirtualPetCat", "Virtual Pet Cat", "Pets", 10000 },
    { "PetFoodDogBasic", "Pet Food (Dog, Basic)", "Pets", 500 },
    { "PetFoodDogPremium", "Pet Food (Dog, Premium)", "Pets", 1250 },
    { "PetFoodCatBasic", "Pet Food (Cat, Basic)", "Pets", 500 },
    { "PetFoodCatPremium", "Pet Food (Cat, Premium)", "Pets", 1250 },
    { "PetFoodSlimeBasic", "Pet Food (Slime, Basic)", "Pets", 500 },
    { "PetFoodSlimePremium", "Pet Food (Slime, Premium)", "Pets", 1250 },
    { "PetMedicineBasic", "Pet Medicine (Basic)", "Pets", 500 },

    { "OrbLightingLesserDark", "Orb - Lesser Dark Lighting", "Orbs", 75000 },
    { "OrbLightingDark", "Orb - Dark Lighting", "Orbs", 75000 },
    { "OrbLightingGreatDark", "Orb - Great Dark Lighting", "Orbs", 75000 },
    { "OrbLightingNone", "Orb - No Lighting", "Orbs", 2000 },
    { "OrbWeatherAuroraBorealis", "Orb - Aurora Borealis", "Orbs", 35000 },
    { "OrbWeatherHearts", "Orb - Hearts Weather", "Orbs", 55000 },
    { "OrbWeatherLightSnow", "Orb - Light Snow", "Orbs", 15000 },
    { "OrbWeatherSnowStorm", "Orb - Snow Storm", "Orbs", 25000 },
    { "OrbWeatherHalloween", "Orb - Halloween Weather", "Orbs", 65000 },
    { "OrbWeatherArmageddon", "Orb - Armageddon Weather", "Orbs", 90000 },
    { "OrbWeatherNone", "Orb - No Weather", "Orbs", 1000 },
    { "OrbWeatherLightRain", "Orb - Light Rain", "Orbs", 10000 },
    { "OrbWeatherHeavyRain", "Orb - Heavy Rain", "Orbs", 15000 },
    { "OrbWeatherSandStorm", "Orb - Sand Storm", "Orbs", 17500 },
    { "OrbWeatherPixelTrail", "Orb - Pixel Trail Weather", "Orbs", 50000 },
    { "CandyOrb", "Candy Orb", "Orbs", 10000 },
    { "WinterOrb", "Winter Orb", "Orbs", 10000 },
    { "CemeteryOrb", "Cemetery Orb", "Orbs", 13000 },
    { "BlueSkyBackgroundOrb", "Summer Sky Orb", "Orbs", 9500 },
    { "ForestOrb", "Forest Orb", "Orbs", 2000 },
    { "StarOrb", "Star Orb", "Orbs", 5000 },
    { "SandOrb", "Sand Orb", "Orbs", 9000 },
    { "NightOrb", "Night Orb", "Orbs", 12000 },
    { "CityOrb", "City Orb", "Orbs", 15000 },

    { "CardPackStarter", "Card Pack - Starter", "Cards", 5000 },
    { "CardPackBasicOne", "Card Pack - Basic One", "Cards", 5000 },
    { "CardPackBasicSmallSet", "Card Pack - Basic Small Set", "Cards", 50000 },

    { "WeaponWiringTool", "Wiring Tool", "Wiring", 7500 },
    { "WiringTriggerLever", "Lever", "Wiring", 250 },
    { "WiringTriggerSwitch", "Switch", "Wiring", 250 },
    { "WiringTriggerButton", "Button", "Wiring", 350 },
    { "WiringTriggerPressurePad", "Pressure Pad", "Wiring", 500 },
    { "WiringTriggerProximitySensor", "Proximity Sensor", "Wiring", 500 },
    { "OnOffLight", "On / Off Light", "Wiring", 100 },
    { "DisappearingBlock", "Disappearing Block", "Wiring", 250 },
    { "WiringLogicGateAND", "AND Gate", "Wiring", 250 },
    { "WiringLogicGateNAND", "NAND Gate", "Wiring", 250 },
    { "WiringLogicGateOR", "OR Gate", "Wiring", 250 },
    { "WiringLogicGateNOR", "NOR Gate", "Wiring", 250 },
    { "WiringLogicGateXOR", "XOR Gate", "Wiring", 250 },
    { "WiringLogicGateXNOR", "XNOR Gate", "Wiring", 250 },
    { "WiringLogicGateNOT", "NOT Gate", "Wiring", 250 },
    { "WiringLogicGateSIGNALDIVIDER", "Signal Divider Gate", "Wiring", 150 },
    { "WiringLogicGateRANDOMIZER", "Randomizer Gate", "Wiring", 500 },
    { "WiringLogicGateTOGGLE", "Toggle Gate", "Wiring", 500 },
    { "WiringLogicGateDELAYTIMER", "Delay Timer Gate", "Wiring", 500 },
    { "WiringLogicGateSIGNALHOLDER", "Signal Holder Gate", "Wiring", 500 },
    { "WiringLogicGateTIMER", "Timer Gate", "Wiring", 500 },

    { "ConsumableValentinesDayPresent", "Heart Box", "Items", 300 },
    { "GoldenPopsicleStatue", "Golden Popsicle", "Items", 2900 },
    { "QuestStarterItemSummer", "Summer Quest Starter", "Items", 1000 },
    { "JetRaceGroupPortal", "Jet Race Group Portal", "Items", 45000 },
    { "ScreenshotForbidden", "Screenshot Forbidden Block", "Items", 100 },
    { "ConsumableCameraWorld", "World Camera", "Items", 100 },
    { "PrizeBox", "Prize Box", "Items", 350 },
    { "AdTV", "Ad TV", "Items", 500 },
    { "Recall", "Recall", "Items", 1000 },
    { "RatingBoard", "Rating Board", "Items", 1200 },
    { "DeathCounter", "Death Counter", "Items", 2000 },
    { "EntrancePortal", "Entrance Portal", "Items", 3750 },
    { "MagicCauldron", "Magic Cauldron", "Items", 5750 },
    { "Recycler", "Recycler", "Items", 7500 },
    { "RuleBot", "Rule Bot", "Items", 10000 },
    { "RuleBotWeapon", "Rule Bot - Weapon", "Items", 10000 },
    { "RuleBotPotion", "Rule Bot - Magic", "Items", 10000 },
    { "RuleBotMount", "Rule Bot - Mount", "Items", 125000 },
    { "BestSetPhotoBooth", "Best Set Photo Booth", "Items", 15000 },
    { "SafeBox", "Bank Bot (Safe Box)", "Items", 17500 },
    { "Replicator", "Replicator", "Items", 20000 },
    { "ColorOMat", "Color-O-Mat", "Items", 25000 },
    { "PWETerminal", "PWE Terminal", "Items", 49000 },
    { "GravityModifier", "Gravity Modifier", "Items", 150000 },

    { "ConsumableRedScroll01", "Red Scroll 1", "Nether", 50 },
    { "ConsumableRedScroll10Pack01", "Red Scroll 1 (10-Pack)", "Nether", 375 },
    { "ConsumableRedScroll02", "Red Scroll 2", "Nether", 75 },
    { "ConsumableRedScroll10Pack02", "Red Scroll 2 (10-Pack)", "Nether", 550 },
    { "ConsumableRedScroll03", "Red Scroll 3", "Nether", 100 },
    { "ConsumableRedScroll10Pack03", "Red Scroll 3 (10-Pack)", "Nether", 750 },
    { "ConsumableRedScroll04", "Red Scroll 4", "Nether", 150 },
    { "ConsumableRedScroll10Pack04", "Red Scroll 4 (10-Pack)", "Nether", 1200 },
    { "ConsumableRedScroll05", "Red Scroll 5", "Nether", 200 },
    { "ConsumableRedScroll10Pack05", "Red Scroll 5 (10-Pack)", "Nether", 1500 },
    { "RedPortal", "Red Portal", "Nether", 9000 },

    { "BlueprintCapeLove", "Blueprint - Cape (Love)", "Blueprints", 390000 },
    { "BlueprintJetPackSnow", "Blueprint - Jetpack (Snow)", "Blueprints", 425000 },
    { "BlueprintNecklaceSpectral", "Blueprint - Necklace (Spectral)", "Blueprints", 175000 },
    { "BlueprintCapeMidnight", "Blueprint - Cape (Midnight)", "Blueprints", 666666 },
    { "BlueprintHatHelmetVisorPWRWhite", "Blueprint - PWR Helmet (White)", "Blueprints", 125000 },
    { "BlueprintGlovesPWRWhite", "Blueprint - PWR Gloves (White)", "Blueprints", 125000 },
    { "BlueprintShoesPWRWhite", "Blueprint - PWR Shoes (White)", "Blueprints", 125000 },
    { "BlueprintSuitPWRWhite", "Blueprint - PWR Suit (White)", "Blueprints", 125000 },
    { "BlueprintHatHelmetVisorPWRYellow", "Blueprint - PWR Helmet (Yellow)", "Blueprints", 125000 },
    { "BlueprintGlovesPWRYellow", "Blueprint - PWR Gloves (Yellow)", "Blueprints", 125000 },
    { "BlueprintShoesPWRYellow", "Blueprint - PWR Shoes (Yellow)", "Blueprints", 125000 },
    { "BlueprintSuitPWRYellow", "Blueprint - PWR Suit (Yellow)", "Blueprints", 125000 },
    { "BlueprintHatHelmetVisorPWRPink", "Blueprint - PWR Helmet (Pink)", "Blueprints", 125000 },
    { "BlueprintGlovesPWRPink", "Blueprint - PWR Gloves (Pink)", "Blueprints", 125000 },
    { "BlueprintShoesPWRPink", "Blueprint - PWR Shoes (Pink)", "Blueprints", 125000 },
    { "BlueprintSuitPWRPink", "Blueprint - PWR Suit (Pink)", "Blueprints", 125000 },
    { "BlueprintHatHelmetVisorPWRBlack", "Blueprint - PWR Helmet (Black)", "Blueprints", 125000 },
    { "BlueprintGlovesPWRBlack", "Blueprint - PWR Gloves (Black)", "Blueprints", 125000 },
    { "BlueprintShoesPWRBlack", "Blueprint - PWR Shoes (Black)", "Blueprints", 125000 },
    { "BlueprintSuitPWRBlack", "Blueprint - PWR Suit (Black)", "Blueprints", 125000 },
    { "BlueprintWeaponGunAK47", "Blueprint - AK47", "Blueprints", 1000000 },
    { "BlueprintGlassesScifiVisorBlack", "Blueprint - Sci-Fi Visor (Black)", "Blueprints", 375000 },
    { "BlueprintNecklaceFrost", "Blueprint - Necklace (Frost)", "Blueprints", 80000 },
    { "BlueprintMaskBunnyDark", "Blueprint - Bunny Mask (Dark)", "Blueprints", 75000 },
    { "BlueprintSuitBunnyDark", "Blueprint - Bunny Suit (Dark)", "Blueprints", 75000 },
    { "BlueprintShoesBunnyDark", "Blueprint - Bunny Shoes (Dark)", "Blueprints", 75000 },
    { "BlueprintHatHelmetVisorPWRRed", "Blueprint - PWR Helmet (Red)", "Blueprints", 125000 },
    { "BlueprintGlovesPWRRed", "Blueprint - PWR Gloves (Red)", "Blueprints", 125000 },
    { "BlueprintShoesPWRRed", "Blueprint - PWR Shoes (Red)", "Blueprints", 125000 },
    { "BlueprintSuitPWRRed", "Blueprint - PWR Suit (Red)", "Blueprints", 125000 },
    { "BlueprintHatHelmetSamuraiBlack", "Blueprint - Samurai Helmet (Black)", "Blueprints", 50000 },
    { "BlueprintMaskSamuraiBlack", "Blueprint - Samurai Mask (Black)", "Blueprints", 35000 },
    { "BlueprintShogunArmorShirt", "Blueprint - Shogun Armor Shirt", "Blueprints", 75000 },
    { "BlueprintShogunArmorPants", "Blueprint - Shogun Armor Pants", "Blueprints", 20000 },
    { "BlueprintShogunShoes", "Blueprint - Shogun Shoes", "Blueprints", 10000 },
    { "BlueprintShogunKatana", "Blueprint - Shogun Katana", "Blueprints", 45000 },
    { "BlueprintShogunCape", "Blueprint - Shogun Cape", "Blueprints", 12000 },
    { "BlueprintHatHelmetVisorPWR", "Blueprint - PWR Helmet", "Blueprints", 125000 },
    { "BlueprintGlovesPWR", "Blueprint - PWR Gloves", "Blueprints", 125000 },
    { "BlueprintShoesPWR", "Blueprint - PWR Shoes", "Blueprints", 125000 },
    { "BlueprintSuitPWR", "Blueprint - PWR Suit", "Blueprints", 125000 },
    { "BlueprintOrbSpaceBackground", "Blueprint - Space Background Orb", "Blueprints", 50000 },
    { "BlueprintNecklaceGlimmer", "Blueprint - Necklace (Glimmer)", "Blueprints", 60000 },
    { "BlueprintMaskTiki", "Blueprint - Tiki Mask", "Blueprints", 100000 },
    { "BlueprintWeaponSwordLaserGreen", "Blueprint - Laser Sword (Green)", "Blueprints", 350000 },
    { "BlueprintWeaponSwordLaserRed", "Blueprint - Laser Sword (Red)", "Blueprints", 350000 },
    { "BlueprintWeaponSwordLaserBlue", "Blueprint - Laser Sword (Blue)", "Blueprints", 350000 },
    { "BlueprintShirtArmorKnight", "Blueprint - Knight Armor Shirt", "Blueprints", 225000 },
    { "BlueprintPantsArmorKnight", "Blueprint - Knight Armor Pants", "Blueprints", 225000 },
    { "BlueprintHatHelmetArmorKnight", "Blueprint - Knight Helmet", "Blueprints", 225000 },
    { "BlueprintWeaponSwordKnight", "Blueprint - Knight Sword", "Blueprints", 350000 },
    { "BlueprintCapeDark", "Blueprint - Cape (Dark)", "Blueprints", 475000 },
    { "BlueprintWeaponSwordLaserClaymore", "Blueprint - Laser Claymore", "Blueprints", 500000 },
    { "BlueprintJetPackPlasma", "Blueprint - Plasma Jetpack", "Blueprints", 500000 },
    { "BlueprintHatHaloBloodBlack", "Blueprint - Blood Halo (Black)", "Blueprints", 600000 },
    { "BlueprintWeaponSwordFlaming", "Blueprint - Flaming Sword", "Blueprints", 725000 },
    { "BlueprintWingsValkyria", "Blueprint - Valkyria Wings", "Blueprints", 750000 },
    { "BlueprintWingsMechanicalGolden", "Blueprint - Mechanical Wings (Golden)", "Blueprints", 950000 },

    { "BlueprintJetPackLongJumpDimensionArms", "Blueprint - Long-Jump Jetpack (Dimension Arms)", "Community", 500000 },
    { "BlueprintCapeUndead", "Blueprint - Undead Cape", "Community", 500000 },
    { "BlueprintWingsRetroButterfly", "Blueprint - Retro Butterfly Wings", "Community", 750000 },
    { "BlueprintJetPackLongJumpAncientGolem", "Blueprint - Long-Jump Jetpack (Ancient Golem)", "Community", 500000 },
    { "BlueprintWingsBackgoyle", "Blueprint - Backgoyle Wings", "Community", 750000 },
    { "BlueprintJetPackLongJumpExplosive", "Blueprint - Long-Jump Jetpack (Explosive)", "Community", 500000 },
    { "BlueprintWingsIonThrusters", "Blueprint - Ion Thruster Wings", "Community", 500000 },
    { "BlueprintBackBackpackWanderer", "Blueprint - Wanderer Backpack", "Community", 335000 },
    { "BlueprintCapeDoggo", "Blueprint - Doggo Cape", "Community", 335000 },
    { "BlueprintWingsMechanical", "Blueprint - Mechanical Wings", "Community", 675000 },
    { "HatBabyCloud", "Baby Cloud Hat", "Community", 255000 },
    { "MaskSynthwave", "Synthwave Mask", "Community", 255000 },
    { "MaskOwl", "Owl Mask", "Community", 255000 },
    { "MaskEarth", "Earth Mask", "Community", 255000 },
    { "BlueprintWeaponSwordPiranha", "Blueprint - Piranha Sword", "Community", 350000 },
    { "BlueprintWeaponSwordTentacle", "Blueprint - Tentacle Sword", "Community", 255000 },
    { "BlueprintWeaponGunTeslapistol", "Blueprint - Tesla Pistol", "Community", 260000 },
    { "HatAlienController", "Alien Controller Hat", "Community", 255000 },
    { "BlueprintWeaponSwordMantel", "Blueprint - Mantel Sword", "Community", 375000 },
    { "BlueprintWeaponAxeOutlander", "Blueprint - Outlander Axe", "Community", 255000 },
    { "KiddieRide", "Kiddie Ride", "Community", 10000 },
    { "BlueprintWeaponSwordBananasplit", "Blueprint - Banana-Split Sword", "Community", 255000 },
    { "BlueprintWeaponStaffSunrise", "Blueprint - Sunrise Staff", "Community", 350000 },
    { "BlueprintWeaponSwordFish", "Blueprint - Fish Sword", "Community", 350000 },
    { "BlueprintWeaponSwordHellhound", "Blueprint - Hellhound Sword", "Community", 375000 },
    { "BlueprintWeaponSwordWolfBlade", "Blueprint - Wolf-Blade Sword", "Community", 380000 },
    { "BlueprintWeaponGunBazookaDubstep", "Blueprint - Dubstep Bazooka", "Community", 1250000 },
    { "FamiliarBubbly", "Bubbly Familiar", "Community", 55000 },
    { "FamiliarLion", "Little Lion Familiar", "Community", 55000 },
    { "FamiliarSugarglider", "Sugar Glider Familiar", "Community", 55000 },

    { "DoorClan", "Clan Door", "Clan", 1000 },
    { "ClanQuestBot", "Clan Quest Bot", "Clan", 7500 },
    { "ClanTotem", "Clan Totem", "Clan", 9000 },
    { "DoorFactionDark", "Faction Door (Dark)", "Clan", 2000 },
    { "DoorFactionLight", "Faction Door (Light)", "Clan", 2000 },
    { "CheckPointFactionDark", "Faction Checkpoint (Dark)", "Clan", 3500 },
    { "CheckPointFactionLight", "Faction Checkpoint (Light)", "Clan", 3500 },
    { "PortalFactionDark", "Faction Portal (Dark)", "Clan", 4000 },
    { "PortalFactionLight", "Faction Portal (Light)", "Clan", 4000 },
    { "BattleScoreBoardFaction", "Faction Battle Scoreboard", "Clan", 8000 },
    { "LockBattleFaction", "Faction Battle Lock", "Clan", 7500 },
    { "LockWorldBattleFaction", "Faction Battle World Lock", "Clan", 9000 },
    { "NecklaceClanLight", "Clan Necklace (Light)", "Clan", 3500 },
    { "NecklaceClanDark", "Clan Necklace (Dark)", "Clan", 3500 },
    { "ShirtHoodieClanLight", "Clan Hoodie (Light)", "Clan", 5000 },
    { "ShirtHoodieClanDark", "Clan Hoodie (Dark)", "Clan", 5000 },
    { "MaskFacePaintClanLight", "Clan Face-Paint (Light)", "Clan", 7500 },
    { "MaskFacePaintClanDark", "Clan Face-Paint (Dark)", "Clan", 7500 },
    { "GlassesVisorClanLight", "Clan Visor (Light)", "Clan", 10000 },
    { "GlassesVisorClanDark", "Clan Visor (Dark)", "Clan", 10000 },
    { "WeaponShieldClanLight", "Clan Shield (Light)", "Clan", 12000 },
    { "WeaponShieldClanDark", "Clan Shield (Dark)", "Clan", 12000 },
    { "MaskGasClanLight", "Clan Gas Mask (Light)", "Clan", 15000 },
    { "MaskGasClanDark", "Clan Gas Mask (Dark)", "Clan", 15000 },
    { "HatCrownClanLight", "Clan Crown (Light)", "Clan", 35000 },
    { "HatCrownClanDark", "Clan Crown (Dark)", "Clan", 35000 },
    { "WeaponSwordClanLight", "Clan Sword (Light)", "Clan", 75000 },
    { "WeaponSwordClanDark", "Clan Sword (Dark)", "Clan", 75000 },
    { "FamiliarClanLight1A", "Clan Familiar (Light)", "Clan", 100000 },
    { "FamiliarClanDark1A", "Clan Familiar (Dark)", "Clan", 100000 },
    { "WingsClanLight", "Clan Wings (Light)", "Clan", 250000 },
    { "WingsClanDark", "Clan Wings (Dark)", "Clan", 250000 },
};
inline constexpr int kPackCount = (int)(sizeof(kPackCatalog) / sizeof(kPackCatalog[0]));

inline void ResetCounter(ZmodUI::State& st) {
    st.store_bought_count = 0;
}

}
